use_frameworks!

platform :ios, '11.0'

inhibit_all_warnings!
install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true

target 'TheRouter_Example' do
  pod 'TheRouter', :path => '../'
  pod 'SnapKit', '5.6.0'
  pod 'Toast', '4.0.0'
  pod 'JKSwiftExtension'
  pod 'TheRouterTestModule', :path => '../Librarys/TheRouterTestModule'
  target 'TheRouter_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
     project.targets.each do |target|
       target.build_configurations.each do |config|
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
         config.build_settings['CODE_SIGN_IDENTITY'] = ''
         if config.name == 'Debug'
             config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO' # strip Linked product
          else
             config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES'
          end
       end
     end
   end
end
