//
//  TheRouter_Mappings.h
//  This file is auto create by scan.py, do not edit this file

#import <Foundation/Foundation.h>



#pragma mark ------------------TheRouterController------------------
static NSString * const kRouterPathTestVcVC = @"test/vc";


#pragma mark -------------TheRouterStoryboardController-------------


#pragma mark ----------------TheRouterSelector---------------
static NSString * const kRouterPathTestJumpSel = @"test/jump";
